### ISSUE TITLE
Modulo 11 - parte 01

### ISSUE THREAD

**Issue by mjacobus** [Augustoqtn/aprender-a-programar#3]
https://curso-lucascaton.club.hotmart.com/lesson/Pb4KVjklOX/criando-aplicacoes-reais-blog-(parte-1)

**Comment by Augustoqtn** [comment]
![Captura de tela de 2021-04-17 13-59-32](https://user-images.githubusercontent.com/79220592/115120721-51fe0200-9f85-11eb-88a3-e83ac1d836be.png)
![Uploading io.png…]()

**Comment by Augustoqtn** [comment]
![oi](https://user-images.githubusercontent.com/79220592/115120739-6b06b300-9f85-11eb-84d7-d01323fbefee.png)

**Comment by Augustoqtn** [comment]
![io](https://user-images.githubusercontent.com/79220592/115120747-71952a80-9f85-11eb-996b-1f1aead55f4a.png)

**Comment by Augustoqtn** [comment]
@mjacobus

**Comment by Augustoqtn** [comment]
como configurar o bootstrap?

**Comment by mjacobus** [comment]
Este erro que tu tem é por que precisa instalar algumas coisas no teu computador para que ele consiga compilar o `pg`.

Em vez de fazer `-d postgres` faz `-d myql` ou então `-d sqlite`.

**Comment by mjacobus** [comment]
Outra coisa, dá uma olhada nos comentários das aulas, e usa eles também para fazer perguntas. Eu acredito que este comentário resolve o teu problema:

  
![Screen Shot 2021-04-17 at 23 43 52](https://user-images.githubusercontent.com/226834/115132474-dfb60d80-9fd6-11eb-944f-5d458f59ab2f.png)

**Comment by mjacobus** [comment]
> como configurar o bootstrap?

ele diz pra olhar a aula de como configurar o boostrap. Então procura fazer aquela aula de novo e se tiver problemas, coloca na issue, que nem tu colocou aqui, @Augustoqtn

**Comment by Augustoqtn** [comment]
ok, obrigado !

**Comment by Augustoqtn** [comment]
![Captura de tela de 2021-04-18 16-16-27](https://user-images.githubusercontent.com/79220592/115157782-77603e00-a061-11eb-8319-53b38bb17015.png)

**Comment by Augustoqtn** [comment]
problema em criar o banco de dados @mjacobus

**Comment by mjacobus** [comment]
É, precisa configurar o banco de dados. O postgress é meio chato. Usa o mysql ou o sqlite.E daí configura as senhas corretas.

**Comment by Augustoqtn** [comment]
![Screen Shot 2021-04-22 at 10 22 50](https://user-images.githubusercontent.com/79220592/115721852-cdc8c780-a354-11eb-81d5-87ac869ecc9d.png)

**Comment by Augustoqtn** [comment]
@mjacobus

**Comment by Augustoqtn** [comment]
https://www.lucascaton.com.br/2020/02/26/instalacao-do-ruby-do-nodejs-no-macos-usando-asdf

**Comment by Augustoqtn** [comment]
![Uploading Screen Shot 2021-04-22 at 11.07.18.png…]()

**Comment by Augustoqtn** [comment]
o brew foi instalado mas quando fui instalar o ASDF deu este erro.

**Comment by Augustoqtn** [comment]
![Uploading Screen Shot 2021-04-22 at 11.09.30.png…]()

**Comment by mjacobus** [comment]
O teu upload não apareceu. 

Não precisa instalar o asdf, eu já instalei.

**Comment by mjacobus** [comment]
pra o comando `rails new blog - d posgresql` é provavelmente que tu colocou um espaço antes do `d` no `-d`.

Não usa o postgree. Não está instalado. Ou usa mysql, ou usa sqlite.

Foi o que eu tinha comentado aqui: https://github.com/Augustoqtn/aprender-a-programar/issues/3#issuecomment-822452213

Pra usar o mysql precisa colocar a opção `-d mysql`
Pra usar o sqlite, é só não colocar a opção `-d ..`.

**Comment by mjacobus** [comment]
Se tu executar o comando do rails e dizer que o rails não tá instalado, dái tu vai precisar executar isto:

```
gem install rails
```

**Comment by Augustoqtn** [comment]
ok

**Comment by Augustoqtn** [comment]
![Screen Shot 2021-04-22 at 12 03 14](https://user-images.githubusercontent.com/79220592/115737709-c01a3e80-a362-11eb-971d-6a214eb808de.png)

**Comment by mjacobus** [comment]
Pesquisa por estes erros no google, ve se consegue entender o motivo.

**Comment by mjacobus** [comment]
Coloca aqui  o resultado do teu comando ```asdf current```

**Comment by Augustoqtn** [comment]
![Screen Shot 2021-04-22 at 14 52 33](https://user-images.githubusercontent.com/79220592/115762973-658cdc80-a37a-11eb-88df-38a88f90af78.png)
