### ISSUE TITLE
Módulo 11, parte 02

### ISSUE THREAD

**Issue by mjacobus** [Augustoqtn/aprender-a-programar#4]
https://curso-lucascaton.club.hotmart.com/lesson/RE4zzpVD4l/criando-aplicacoes-reais-blog-(parte-2)

**Comment by mjacobus** [comment]
@Augustoqtn qualquer dúvida escreve tua dúvida aqui.

**Comment by Augustoqtn** [comment]
![Screen Shot 2021-04-23 at 10 03 53](https://user-images.githubusercontent.com/79220592/115875293-717cab00-a41b-11eb-83e8-0b736a8403f1.png)

**Comment by mjacobus** [comment]
Asssite o vídeo aqui de novo: https://github.com/Augustoqtn/aprender-a-programar/issues/2

Ele explica isto.

**Comment by Augustoqtn** [comment]
foi isso que eu fiz, mas olhar novamente. obg

**Comment by Augustoqtn** [comment]
resolvido. obg...

**Comment by mjacobus** [comment]
Qual tinha sido o problema? Registra aqui.
