### ISSUE TITLE
Criar uma PR (Pull Request) para corrigir o seguinte erro

### ISSUE THREAD

**Issue by mjacobus** [Augustoqtn/aprender-a-programar#53]
Remover o d da palavra project https://github.com/mjacobus/.dotfiles/blob/master/profile.d/zshell/autocompletions.conf#L3

Passos:

- [ ] Fazer fork do projeto
- [ ] Clonar o fork `cd ~/Projects/; git clone git@github.com:Augustoqtn/.dotfiles.git`
- [ ] Abrir o projeto no vs code
- [ ] Criar um branch para corrigir o erro de digitação: 
```bash
cd Projects # entra na pasta (IMPORTANTE)
git branch corrige-erro-digitacao # cria o branch
git checkout corrige-erro-digitacao # troca o branch
```
- [ ] Alterar o arquivo `profile.d/zshell/autocompletions.conf` e corrigir a linha 3
- [ ] Adiciona o arquivo para a "caixa" `git add profile.d/zshell/autocompletions.conf`
- [ ] Verifica se deu certo, presta atençÃo nas mensagens: `git status -s`
- [ ] Commita `git commit -m "corrige erro de digitação"
- [ ] Faz push pro github `git push origin corrige-erro-digitacao`
- [ ] Vai no github e pede para fazer uma PR (pull request) - vai aparecer pra ti quando tu visitar a página do teu fork ou a minha - não lembro bem
- [ ] Cria a PR

**Comment by Augustoqtn** [comment]
![Uploading Screen Shot 2021-04-22 at 14.28.50.png…]()

**Comment by Augustoqtn** [comment]
este erro aparece quando vou fazer o push

**Comment by mjacobus** [comment]
Cuida quer teus uploads não estão funcionando. Depois de postar o comentário olha como ele ficou.

**Comment by mjacobus** [comment]
Resolvido em https://github.com/mjacobus/.dotfiles/pull/19
