### ISSUE TITLE
Aprender "workflow" - como trabalhar

### ISSUE THREAD

**Issue by mjacobus** [Augustoqtn/aprender-a-programar#57]
Como trabalhar:

1. use o master e tenha certeza que ele está atualizado

```
# dentro da pasta do projeto, sempre

git checkout master # troca pro master
git pull origin master # atualiza o master com o github
```

2. Cria um novo branch:

```
git branch nome-do-branch # cria branch
git checkout nome-do-branch # troca pro branch
```

3. Trabalha no branch

```
git add arquivo1.txt arquivo2.txt
git commit -m "Altera arquivo 1 e 2"
git add arquivo3.txt
git commit -m "Altera arquivo 3"

git push origin nome-do-branch # manda para o github novos commits para o github
```

4. Cria uma PR no github. Visita a págian do projeto e aceita a sugestão de comparar e fazer uma PR.

Opcional: Continua trabalhando na mesma PR

```
git add arquivo1.txt arquivo2.txt
git commit -m "Altera arquivo 1 e 2"
git add arquivo3.txt
git commit -m "Altera arquivo 3"

git push origin nome-do-branch # manda para o github novos commits para o github
```

5. Se tiver tudo certo, faz o merge da PR pelo github.

6. Volta para o master e atualiza ele (mesmo que o passo 1)

7. Remove o branch que já foi feito o merge:

```
git branch -d nome-do-branch
```

Se o git reclamar que não pode deletar o branch, pode fazer assim:

```
git branch -D nome-do-branch # nota o D maiúsculo
```

Pronto. Trabalho pronto. Começa de novo.

## Observações:

- Presta atenção nas mensagens
- Cuida pra comitar só o que tu quiser
- Faz `git log` depois dos commits pra ver como o teu commit alterou o histórico
- Faz `git show` pra mostrar o que tu commitou
- Faz `git diff` pra ver o que foi alterado e está fora da caixa
- Faz `git diff --cached` pra ver o que foi alterado e colocado dentro da caixa
- Aprende que nome da "caixa" é "stage"
- Lembra de fazer `git status` ou `git status -s` pra ver como estão as coisas.

**Comment by Augustoqtn** [comment]
![Uploading Captura de Tela 2021-04-26 às 09.24.18.png…]()

**Comment by Augustoqtn** [comment]
![Captura de Tela 2021-04-26 às 09 24 18](https://user-images.githubusercontent.com/79220592/116081974-4390a400-a671-11eb-9498-6f3a80dfde7f.png)

**Comment by Augustoqtn** [comment]
tive duvida neste passo 3

**Comment by mjacobus** [comment]
Conseguiu entender já @Augustoqtn ?
