### ISSUE TITLE
segunda 26/04

### ISSUE THREAD

**Issue by Augustoqtn** [Augustoqtn/aprender-a-programar#58]
consegui fazer um push para o git hub
consegui configurar o bootstrap em uma aplicacao rails
terminei de arrumar a parte um do meu blog

pretendo melhor a minha atencao e ter mais cuidado com as coisas que faco
pretendo aprender a usar o git .

**Comment by mjacobus** [comment]
👍  Muito bom 👏 
Foi um dia produtivo.
